### ISSUE TITLE
Issues (on Linux) with KeepassXC upgrade to version 2.7.3

### ISSUE THREAD

**Issue by mdonz** [kkapsner/keepassxc-mail#77] opened 2022-10-25 18:46 UTC
Being a happy user of keepassxc-mail for a long time (Ubuntu 22.04, KeepassXC 2.7.1, KeePassXC-Browser 1.8.3, keepassxc-mail 1.3), I experience issue with a recent upgrade for KeepassXC from former version 2.7.1 to the new version 2.7.3.
There is a discussion going on here: https://github.com/keepassxreboot/keepassxc/issues/8634

The described workaround to get it going is to "Delete the old proxy socket from XDG_RUNTIME_DIR". I did so and my browser integrations (Firefox and Chromium) are working again as expected with the new Keepassxc version 2.7.3 but I cannot get keepassxc-mail working.

Have reverted back to Keepassxc 2.7.1 for now again with everything (Firefox, Chromium & Thunderbird with keepassxc-mail working) but wonder what might be need for keepassxc-mail?

Thanks for a great add-on.

**Comment by kkapsner** [comment] 2022-10-26 10:27
Please try [keepassxc-mail-1.3.1.zip](https://github.com/kkapsner/keepassxc-mail/files/9868559/keepassxc-mail-1.3.1.zip)

**Comment by marcinp2** [comment] 2022-10-26 14:31
I confirm the same issue. Version 2.7.3 and KeePassXC-Browser: 1.8.3 doesn't work at all.
The symptoms:
 - connection is closing between them
 - KeePass icon at login pages is unexpected hiding
 - auto filling doesn't work
 - pop-up menu and fill pass feature doesn't work

**Comment by kkapsner** [comment] 2022-10-26 17:47
@marcinp2: I think you are in the wrong git repository. This is for keepassXC-mail (mail extension for Thunderbird) and not keepassXC-browser

@nbrucy: do you see anything in the console (Ctrl + Shift + J)?

**Comment by mdonz** [comment] 2022-10-26 20:12
I have upgraded to  keepassxc-mail-1.3.1.zip (while using KeepassXC version 2.7.1), then shutdown browser and Thunderbird (so no more active keepassxc-proxy processes after that). 

cd $XDG_RUNTIME_DIR
michael@TWT039LT:/run/user/1001$ ls -la
total 8
drwx------ 17 michael michael 580 Oct 26 07:00 .
drwxr-xr-x  3 root    root     60 Oct 24 08:34 ..
.. cut..
srwx------  1 michael michael   0 Oct 26 07:00 org.keepassxc.KeePassXC.BrowserServer
I then uninstalled KeepasXC 2.7.1 and removed manually "org.keepassxc.KeePassXC.BrowserServer".

After upgrade to KeepassXC 2.7.3 and starting it, it looks good (I believe):
michael@TWT039LT:/run/user/1001$ ls -la
total 8
drwx------ 17 michael michael 580 Oct 27 08:56 .
drwxr-xr-x  3 root    root     60 Oct 24 08:34 ..
.. cut ..
lrwxrwxrwx  1 michael michael  81 Oct 27 08:56 org.keepassxc.KeePassXC.BrowserServer -> /run/user/1001/app/org.keepassxc.KeePassXC//org.keepassxc.KeePassXC.BrowserServer
Then starting Firefox, the web browser integration is working well so far. Then starting Thunderbird, it sits forever on trying to get access to email account, load messages, etc. Below is the output from the TB console. Hope that helps. 

 

09:00:08.400 1666814408400	addons.xpi	WARN	Checking /usr/lib/thunderbird/distribution/extensions for addons
09:00:09.987 This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
hiddenWindow.html
09:00:10.113 1666814410113	addons.webextension.{2ab1b709-ba03-4361-abf9-c50b964ff75d}	WARN	Loading extension '{2ab1b709-ba03-4361-abf9-c50b964ff75d}': Reading manifest: Warning processing background.scripts: An unexpected property was found in the WebExtension manifest.
09:00:10.909 This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
46 AddonRepository.jsm:97:12
09:00:11.249 Successfully loaded OpenPGP library librnp.so version 0.16+git20220124.f06439f7.MZLA from /usr/lib/thunderbird/librnp.so RNPLib.jsm:100:15
09:00:11.674 Found 0 public keys and 0 secret keys (0 protected, 0 unprotected) RNPLib.jsm:301:15
09:00:11.839 services.settings: Failed to load last_modified.json: TypeError: NetworkError when attempting to fetch resource. Utils.jsm:330
09:00:11.867 Successfully loaded optional OpenPGP library libgpgme.so.11 from system's standard library locations GPGMELib.jsm:69:13
09:00:11.868 gpgme version: 1.16.0-unknown GPGMELib.jsm:241:15
09:00:12.188 Trying to load /usr/lib/thunderbird/libotr.so OTRLib.jsm:64:11
09:00:12.188 Trying to load libotr.so from system's standard library locations OTRLib.jsm:64:11
09:00:12.188 Trying to load libotr.so.5 from system's standard library locations OTRLib.jsm:64:11
09:00:12.189 Trying to load libotr.so from system's standard library locations OTRLib.jsm:64:11
09:00:12.189 Error: Cannot load required OTR library
    loadExternalOTRLib resource:///modules/OTRLib.jsm:109
    init resource:///modules/OTRLib.jsm:115
    once resource:///modules/OTR.jsm:118
    init resource:///modules/OTR.jsm:139
    init resource:///modules/OTRUI.jsm:256
    nsIPrompt_promptUsernameAndPassword resource:///modules/MsgAsyncPrompter.jsm:553
    promptAuth resource:///modules/MsgAsyncPrompter.jsm:479
    promptAuth resource:///modules/calendar/utils/calAuthUtils.jsm:236
    onPromptStart resource:///modules/calendar/utils/calAuthUtils.jsm:267
    onPromptStartAsync resource:///modules/calendar/utils/calAuthUtils.jsm:263
    _promiseAuthPrompt resource:///modules/MsgAsyncPrompter.jsm:54
    _promiseAuthPrompt resource:///modules/MsgAsyncPrompter.jsm:52
    run resource:///modules/MsgAsyncPrompter.jsm:77
OTR.jsm:127:15
09:00:12.214 tb.account.size_on_disk - Trying to set an unsigned scalar to a negative number. 2
09:00:12.361 No chrome package registered for chrome://sendtocategory/content/category_tools.js 2
09:00:12.497 This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”.
background.html
09:00:12.692 WebExtensions: KeePassXC-Mail: unable to get smtpEnterPasswordPromptTitle from bundle compose 2 implementation.js:34
09:00:12.693 WebExtensions: KeePassXC-Mail: unable to get imapEnterPasswordPromptTitle from bundle imap implementation.js:34
09:00:12.693 WebExtensions: KeePassXC-Mail: unable to get pop3EnterPasswordPromptTitle from bundle local 2 implementation.js:34
09:00:12.694 WebExtensions: KeePassXC-Mail: unable to get loginDialog.label from bundle wcap 2 implementation.js:34
09:00:12.694 WebExtensions: KeePassXC-Mail: unable to get PromptUsernameAndPassword2 from bundle commonDialog 2 implementation.js:34
09:00:12.695 WebExtensions: KeePassXC-Mail: unable to get PromptPassword2 from bundle commonDialog implementation.js:34
09:00:12.695 WebExtensions: KeePassXC-Mail: unable to get CertPassPromptDefault from bundle pipnss implementation.js:34
09:00:13.778
JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 1520 of the JSON data 2 subprocess_common.jsm:495

**Comment by mdonz** [comment] 2022-10-26 20:23
I have now converted KeepassXC back to version 2.7.1 (left keepassxc-mail on version 1.3.1).

Everything seems to be working in Thunderbird but now having a look at the TB console, this looks almost identical to what I uploaded earlier. At that time I though that the lines of "WebExtensions: KeePassXC-Mail: unable to get xxxxEnterPasswordPromptTitle" where indicating the issues - but these lines still appear again when TB seems to be working,

The only real difference might be this line (not appearing under a working situation):
JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 1520 of the JSON data 2 subprocess_common.jsm

**Comment by kkapsner** [comment] 2022-10-27 16:06
The `unable to get` messages are normal. They are there for backward compatibility with older Thunderbird versions.

I think I will spin up an Ubuntu VM and try to reproduce the problem. But the `unexpected whitespace` message sounds not good.

**Comment by kkapsner** [comment] 2022-10-27 20:43
That's bad. This is a core function of the native messaging that is provided by Mozilla. And the JSON is provided by KeePassXC. So I cannot change any of the involved programs.

@droidmonkey & @varjolintu: I was able to reproduce the same issue in Firefox 106.0.2 with keepassxc-browser 1.8.3: 
![grafik](https://user-images.githubusercontent.com/1105157/198392162-ca279248-edaa-43b6-bd89-c1f93ffeee81.png)

It might be related to all the other problems with 2.7.3. (e.g. https://github.com/keepassxreboot/keepassxc/issues/8634, https://github.com/keepassxreboot/keepassxc-browser/issues/1751)
I found out that the JSON created by the proxy (or KeePassXC - not sure where the JSON is created) and sent to the extension may contain invalid JSON:
```JSON
{"action":"get-logins","message":"9vb[...]wAZ","nonce":"Agn[..]ZM"}{}
```
Notice the additional `{}` at the end.

In Thunderbird I'm able to get this output by executing the following in the console (Ctrl + Shift + J):
```JavaScript
var {BaseProcess} = Cu.import("resource://gre/modules/subprocess/subprocess_common.jsm");
BaseProcess.create = function create(options){
  let worker = this.getWorker();
  
  return worker.call("spawn", [options]).then(({ processId, fds, pid }) => {
    console.log("creating BaseProcess");
    var baseProcess = new this(worker, processId, fds, pid);
    BaseProcess.last = baseProcess;
    baseProcess.stdout.readJSON =  function readJSON(length) {
      if (!Number.isInteger(length) || length <= 0) {
        throw new RangeError("Length must be a positive integer");
      }
      
      return this.readString(length).then(string => {
        try {
          return JSON.parse(string);
        } catch (e) {
          console.log("Invalid JSON:", string);
          e.errorCode = SubprocessConstants.ERROR_INVALID_JSON;
          throw e;
        }
      });
    };
    return baseProcess;
  });
}
```
I was not able to inject this code into Firefox.

Some additional information that might help pin the problem down: it only happens on database entries where you "remembered" the choice of allowing the access. If the "Browser request access" pops up the message is fine.

**Comment by droidmonkey** [comment] 2022-10-27 20:55
Yah we know 1.8.3 extension is flaky, there is a fix coming.

**Comment by kkapsner** [comment] 2022-10-27 20:59
@droidmonkey: I don't think it's the extension. In keepassxc-mail I'm currently using the files from 1.8.0.
This JSON is not generated by the extension but by the other end of the native messaging - i.e. KeePassXC itself.

@mdonz and @nbrucy: I think the only solution for you is at the moment to go back to 2.7.1

**Comment by mdonz** [comment] 2022-10-27 21:04
@kkapsner I much appreciate your work and help with this. I will stay with 2.7.1 for now. Have just observed an interesting detail (under 2.7.1) which I will raise separately.

**Comment by droidmonkey** [comment] 2022-10-27 21:16
There is a separate problem with 2.7.3 for some Linux distributions where the socket file is not created correctly in the runtime directory. See here for a workaround: https://github.com/keepassxreboot/keepassxc/issues/8634#issuecomment-1290490385

**Comment by kkapsner** [comment] 2022-10-27 21:23
I started with a complete new VM and never installed 2.7.1 there.
In this folder there is only the snap.keepassXC:
![grafik](https://user-images.githubusercontent.com/1105157/198400821-8285d8f1-f0bb-45ae-ae2c-267f0d408a20.png)

**Comment by kkapsner** [comment] 2022-10-27 21:26
The initial connection is working - it just breaks after the invalid JSON:
![grafik](https://user-images.githubusercontent.com/1105157/198401172-9fff983d-9e32-4bab-91a1-81b56098da30.png)

I'm also able to reproduce the problem with keepassxc-browser 1.8.0:
![grafik](https://user-images.githubusercontent.com/1105157/198401369-e8dcf32f-95e0-4b1f-878f-a170d6f25013.png)

**Comment by kkapsner** [comment] 2022-10-27 21:46
Just checked: not related to snap - problem also present with PPA version

**Comment by kkapsner** [comment] 2022-10-27 21:51
@droidmonkey: is there a way to tell KeePassXC to output the native messaging communication? Or do I have to implement a proxy for that?

**Comment by mdonz** [comment] 2022-10-27 21:51
FYI all of my installed packages are from PPA. No snap involved here.

**Comment by kkapsner** [comment] 2022-10-27 22:05
It's also broken in my Windows VM.

**Comment by droidmonkey** [comment] 2022-10-27 22:13
You have to run keepassxc in a debugger and break on the message send function to see exactly what we are sending. I am fairly confident we never send a blank json message (`{}`). You can also use this Python library to dynamically interact with the browser service: https://github.com/hrehfeld/python-keepassxc-browser

**Comment by kkapsner** [comment] 2022-10-27 22:40
Thanks for the info - will toy around with that.
In the meantime I played with a Windows tool to intercept native messaging. There seems to be blank JSON messages:
![grafik](https://user-images.githubusercontent.com/1105157/198411196-46363b0d-e57b-4132-86ae-20c79bcb2108.png)
But the message lengths seem correct - so there is also a problem with the code in Thunderbird.

**Comment by droidmonkey** [comment] 2022-10-27 22:43
Cool tool, where can it be found?

**Comment by kkapsner** [comment] 2022-10-27 22:44
https://textslashplain.com/2022/01/08/debug-native-messaging/
No guarantee it's not malicious... I just run it in a VM.

**Comment by kkapsner** [comment] 2022-10-27 23:14
@droidmonkey: KeePassXC is sending wrong data:
![grafik](https://user-images.githubusercontent.com/1105157/198414813-4780f3d4-a8c3-42cd-bdf4-4cf39f094ce8.png)
No idea what causes the problem. But I have to try several get-logins to get the problem. I guess it's some sort of racing condition.

**Comment by kkapsner** [comment] 2022-10-27 23:18
I actually would be able to to mess with Thunderbird code to fix these messages. But this will not be part of an official release (I gues I would make an additional extension for that).

And it would still leave Firefox broken.

So I would rather prefer KeePassXC to be fixed. @droidmonkey: is there anything more that I can provide you to find the culprit?

**Comment by kkapsner** [comment] 2022-10-27 23:20
@ericlaw1979: thanks for the great tool

**Comment by varjolintu** [comment] 2022-10-28 04:33
If something sends blank JSON messages, it's KeePassXC 2.7.3. Everything would work normally with 2.7.1.

**Comment by droidmonkey** [comment] 2022-10-28 08:52
Is that part of the async dialog problem?

**Comment by varjolintu** [comment] 2022-10-28 09:02
@droidmonkey Yes. It's related to that.

**Comment by mdonz** [comment] 2022-10-30 04:54
Good news: (Ubuntu 22.04) - I just applied the update to KeepassXC 2.7.4 and so far, my browser integration is working for Firefox and keepassxc-mail under Thunderbird!
Hoping this will continue. Thanks to all involved!

**Comment by kkapsner** [comment] 2022-10-30 16:26
I do not see any empty messages with 2.7.4. So I would close this issue.

One last question @droidmonkey and @varjolintu: the empty messages itself were not the problem but  that two messages were concatenated and in the protocol the length of the message was therefore wrong (see my last screenshot). Was this also introduced by the asynchronous dialog? Or could that happen again (e.g when the browser and Thunderbird are talking to keepassXC at the exact same time or something similar)?

**Comment by droidmonkey** [comment] 2022-10-30 17:35
It was likely a double tap of json messages, a coding error. We sent the real message and an empty one. I thought the native message debugger showed the empty message was sent with the correct length though.

**Comment by varjolintu** [comment] 2022-10-30 18:21
It is exactly how @droidmonkey described it. The real answer was sent directly to the same socket as the empty message, which caused this error.

**Comment by kkapsner** [comment] 2022-10-30 20:54
> It was likely a double tap of json messages, a coding error. We sent the real message and an empty one. I thought the native message debugger showed the empty message was sent with the correct length though.

Most of the time it showed the correct length. In these cases Thunderbird handled them correctly. But sometimes the length was not correct (in the [screenshot above](https://github.com/kkapsner/keepassxc-mail/issues/77#issuecomment-1294221651) the real message is 431 bytes long + the empty message = 433 => breaking the native messaging connection)

**Closed** 2022-10-31 11:53 UTC
Labels: bug
